### DISCUSSION TITLE
How to deal with temperature values going `unknown` ? - create a trigger based template sensor

### DISCUSSION THREAD

**Discussion by Anto79-ops** [firstof9/ha-renogy#26] [General]
Since the battery temperature does not change often, you may have noticed that the temperature entities goes to `unknown`  after a while (hours maybe?) untill the temperature updates again. This is also true in the DC Home app, the battery temperature may appear as "--" instead of a number. It will remain like this untill the temperature changes. Sometimes the temperature does not change for hours, so having unknown on your dashboard cards or automations is not desirable.

To solve this in Home Assistant, I used a trigger based template sensor. For example, here the one I created for my 100 Ah Li self-heating battery

```
template:
  - trigger:
      trigger: state
      entity_id: sensor.rbt100lfp12sh_g1_average_temperature
    condition:
      - condition: template
        value_template: "{{ is_number(states('sensor.rbt100lfp12sh_g1_average_temperature')) }}"
    sensor:
      - name: Renogy Battery Temperature last known value
        unique_id: 14f1a5a3-8482-42d9-90d6-7d8f2c66e603
        state_class: measurement
        unit_of_measurement: °C
        device_class: temperature
        state: "{{ states('sensor.rbt100lfp12sh_g1_average_temperature') }}"
```

This creates a second temperature entity for your battery BUT it only updates when the orignal entity changes to a number.

For example:

![image](https://github.com/user-attachments/assets/6b81fde5-1792-423f-b1d8-e4bd5ac15492)

Replace with your own entity and ID and then click reload template entities.
